== Tests

Für Tests wird das Framework NUnit verwendet. Im Projekt `CaaS.Core.Test` sind
Tests für das Projekt `CaaS.Core` implementiert. Wichtig ist uns, dass wir eine
hohe Testabdeckung mit sinnvollen Tests erzielen. Dabei wurde noch nicht
quantifiziert, welche Testabdeckung wir erreichen wollen.

Bei jedem Push in `main` oder Pull-Request in `main` werden alle Tests durch unsere CI/CD-Pipeline ausgeführt. Dabei wird mit Docker-Compose eine Datenbank-Container und ein Runner-Container erstellt.
Anschließend führt der Runner die Tests gegen die Datenbank aus. Das Ergebnis ist in Github zu sehen.
Bei fehlerhaften Tests erhalten die Projektmitarbeiter eine Email.

=== Integration-Tests

Integration-Tests erwarten einen laufenden Container der `caas-dev-db` mit
initialen Daten eingespielt durch die Datei `init.sql`. Darum kümmert sich das
Image des Containers selbstständig. Damit der Container nicht für jeden Test
erneut erstellt werden muss, haben wir ein `Rollback`-Attribut implementiert.
Damit kann man Tests annotieren um keine Transaktion auf die Datenbank
auszuführen.

Es wurden Versuche gemacht, das Framework `testcontainers` zu verwenden. Dieses
startet automatisiert einen beliebigen Dockercontainer für Tests. Aufgrund von
Performanceproblemen wurde dieses Vorgehen aktuell pausiert. Vermutlich benötigt
das Framework weitere Konfiuration. Es ist angedacht, dieses Framework im
nächsten Schritt weiter zu evaluieren.

Integrationstests werden mit "Integration" getaggt.

.Voraussetzungen für erfolgreiche Integrationstests 
* Frischer Container aus dem
Image ./src/CaaS/Docker/db_dev/Dockerfile


=== UNIT-Tests

Die UNIT-Test benötigen keine besonderen Vorbereitung für eine korrekte
Ausführung.

UNIT-Tests werden mit "Unit" getaggt.

=== System-Tests

Systemtests erwarten Datensätze aus dem Container `caas-dev-db` und sind mit `System` getaggt.
Hier werden sinnvolle Anwendungsfälle automatisiert überprüft.

==== Use Case: create Discount 

Klasse: CaaS.Api.Test.UseCases.CreateDiscountUseCase

> Ich, als Shopbetreiber, will eine neue Rabattregel und Rabattaktion einführen. Anschließend möchte ich einen konkreten Rabatt für meinen Shop erstellen.

. Rabattaktion erstellen
.. Alle verfügbaren Rabattaktionen laden
.. Passende Rabattaktion auswählen
.. Rabattaktion mit gewünschten Parametern erstellen
.. Id der neuen Rabattaktion speichern
. Rabattregel erstellen
.. Alle verfügbaren Rabattregeln laden
.. Passende Rabattregel auswählen
.. Rabattregel mit gewünschten Parametern erstellen
.. Id der neuen Rabattregel speichern
. Rabatt erstellen
.. Rabatt mit den gespeicherten Ids für Rabattaktion und Rabattregel erstellen
.. Neue Id speichern
.. Rabatt laden mit gespeicherter Id
.. Vergleichen, ob die dazugehörige Rabattregel und Rabattaktion valide sind.

==== Use Case: Bestell- und Bezahlprozess
Klasse: CaaS.Api.Test.UseCases.PaymentUseCase

> Ich, als Kunde, will ein Produkt zum Warenkorb hinzufügen. Anschließend möchte ich das Produkt bestellen und bezahlen.

. Warenkorb erstellen.
. Produkt mit Warenkorb verknüpfen.
. Kunde mit Warenkorb verknüpfen.
. Bestellung anlegen.
. Die Bestellung bezahlen.