version: '3.4'

services:
  caas.api:
    image: ${DOCKER_REGISTRY-}caasapi
    build:
      context: .
      dockerfile: CaaS.Api\Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - caasnetdebug

  db:
    build:
      context: '..\'
      dockerfile: Dev-Db-Dockerfile
    restart: always
    container_name: db-debug
    environment:
      - MYSQL_DATABASE=caas
      - MYSQL_USER=service
      - MYSQL_PASSWORD=mypass123
      - MYSQL_ROOT_PASSWORD=mypass123
      - DB_HOST=db
      - MYSQL_HOST=db
      - MYSQL_ROOT_HOST=db
    ports:
      - 3306:3306
    networks:
      - caasnetdebug
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 2s
      retries: 20
networks:
  caasnetdebug: