version: '3'

services:
  tests:
    build:
      context: .
      dockerfile: Test-Dockerfile
    container_name: caas-int-tests
    environment:
      - environment=integration
    networks:
      - caasnet
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: .
      dockerfile: Dev-Db-Dockerfile
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=caas
      - MYSQL_USER=service
      - MYSQL_PASSWORD=mypass123
      - MYSQL_ROOT_PASSWORD=mypass123
      - DB_HOST=db
      - MYSQL_HOST=db
      - MYSQL_ROOT_HOST=db
      #- MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    networks:
      - caasnet
        # aliases:
        #   - db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 1s
      retries: 20
networks:
  caasnet:
