version: '3.4'

services:
  caas.api:
    image: ${DOCKER_REGISTRY-}caasapi
    build:
      context: .
      dockerfile: CaaS.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - caasnetdevelopement

  db:
    build:
      context: .
      dockerfile: Dev-Db-Dockerfile
    restart: always
    container_name: db-development
    environment:
      - MYSQL_DATABASE=caas
      - MYSQL_USER=service
      - MYSQL_PASSWORD=mypass123
      - MYSQL_ROOT_PASSWORD=mypass123
      - DB_HOST=db
      - MYSQL_HOST=db
      - MYSQL_ROOT_HOST=db
    ports:
      - 3306:3306
    networks:
      - caasnetdevelopement
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - caasnetdevelopement

networks:
  caasnetdevelopement: