# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: integration test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build database image
        run: docker build --tag caas-dev-db ./src/CaaS/Docker/db_dev && d
      - name: Run docker image
<<<<<<< HEAD
        run: docker run -d --name caas-dev-db -p 3306:3306 caas-dev-db
      - name: Wait for db finish
        run: sleep 30s
=======
        run: docker run ---name caas-dev-db -d -p 3306:3306 caas-dev-db
>>>>>>> 2ea1dce7dcd46ba48c4eddc3057f5b61b4bd047d
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/Caas/
      - name: Build
        run: dotnet build --no-restore ./src/Caas/
      - name: Test
        run: dotnet test --no-build --verbosity normal ./src/Caas/

  
